import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Index: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diploi Demo | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Diploi!</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Development &rarr;</h2>
            <p>Connect with VSCode Remote SSH, nothing to set up</p>
          </a>

          <Link href="/redis">
            <span className={styles.card}>
              <h2>Redis &rarr;</h2>
              <p>A Redis cluster is included and can be used for session handling or other stuff</p>
            </span>
          </Link>

          <Link href="/postrgresql">
            <span className={styles.card}>
              <h2>PostgreSQL &rarr;</h2>
              <p>A basic PostgreSQL instance is included, enjoy.</p>
            </span>
          </Link>

          <Link href="/more">
            <span>
              <h2>More stuff &rarr;</h2>
              <p>Jingle Bells XXX and more and more and more.....</p>
            </span>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Index;
