import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useEffect, useState } from 'react';

const RedisPage: NextPage = () => {
  const [items, setItems] = useState([]);

  useEffect(() => {
    (async () => {
      const fetchResponse = await fetch(`/api/todo`, {
        method: 'POST',
        headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
      });
      const items = await fetchResponse.json();
      console.log(items);
      setItems(items);
    })();
  }, []);

  const addItem = async () => {
    const fetchResponse = await fetch(`/api/todo-add`, {
      method: 'POST',
      headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    });
    const items = await fetchResponse.json();
    setItems(items);
  };

  const reset = async () => {
    const fetchResponse = await fetch(`/api/todo-reset`, {
      method: 'POST',
      headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    });
    const items = await fetchResponse.json();
    setItems(items);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Diploi Demo | Redis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Diploi!</Link>
        </h1>

        <p className={styles.description}>
          Redis Powered
          <br />
          TODO List
        </p>

        <div style={{ minHeight: '397px' }}>
          <div style={{ minHeight: '200px' }}>
            {items.map((item, i) => (
              <div key={i}>{item}</div>
            ))}
          </div>
          <div style={{ marginTop: '1rem' }}>
            <button onClick={addItem}>Add</button> &nbsp;
            <button onClick={reset}>Reset</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default RedisPage;
